@startuml
package "backend" {
    class BackendApplication
    class BookingService
    class JsonTreatmentRepository
    class RestBookingController
    class RestTreatmentController
    class TreatmentService
    class TreatmentRepository
}

package "core" {
    package "json" {
        class JsonFilehandling
        class TimeSlotOverview
        package "internal" {
            class BookingDeserializer
            class BookingSerializer
        }
    }
    class PriceCalculator
    class Treatment
    class TimeSlot
    class WeeklyTimeSlots
}

package "ui" {
    class HairdresserApp
    class BookingController
    class TreatmentController
    class FrontBookingService
    class FrontTreatmentService
}

backend ..> core : uses
ui ..> backend : uses
ui ..> core : uses

@enduml
